[package]
name = "dashy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.101"
crossterm = "0.29.0"
ratatui = "0.30.0"
sysinfo = "0.38.1"
tokio = { version = "1.49.0", features = ["full"] }
